### ISSUE TITLE
$trim of single Space leads to a index out of bounds exception

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#370] opened 2024-06-09 07:00 UTC
If you execute this:

`(
$header:="";
$name:="";
$trim($header & " " & $name);
)`

you get a 
`Index -1 out of bounds for length 0`

error. Expected output would be an empty string.

Actual:
![image](https://github.com/dashjoin/platform/assets/47058152/5eeb0d71-e664-4b86-a3b2-99d6c87c7890)

Expected:
![image](https://github.com/dashjoin/platform/assets/47058152/c443983a-9a33-4d8e-8143-414ec9ed4702)

**Comment by aeberhart** [comment] 2024-06-11 08:13
duplicate of https://github.com/dashjoin/jsonata-java/issues/34
will be fixed in 5.2

**Closed by aeberhart** 2024-06-11 08:13 UTC
