### ISSUE TITLE
Input fields - Expression to generate options, does not "know" variables

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#371] opened 2024-06-09 07:26 UTC
To generate the input options for an input field i use this expression:
`(
$query($.variable.db, "q_client_getSpecies", {"clientId":"92b4f138-c1d9-45c1-ae82-a6775a2657c3"}).species
)`

$.variable.db is set to our database (wooltest) - and the preview also works well:
![image](https://github.com/dashjoin/platform/assets/47058152/b5da333c-5bb0-4dae-aaa7-9465903cb7cc)

But when you save, the input shows:
![image](https://github.com/dashjoin/platform/assets/47058152/ba81e5ad-5cdc-48e5-ba86-2bf305391895)

If you hardcode the database:
`(
$query("wooltest", "q_client_getSpecies", {"clientId":"92b4f138-c1d9-45c1-ae82-a6775a2657c3"}).species
)`

it works.

It seems that the context is not passed, because also if i execute this in the preview:

![image](https://github.com/dashjoin/platform/assets/47058152/65cd4dc8-6877-4d33-9885-ba16572068eb)

you see two results, but when saving, the choices are empty:

![image](https://github.com/dashjoin/platform/assets/47058152/49aa9c8b-352f-41a4-a971-0e89ac0683f0)

If you "Hardcode" the client Id - it works.

**Comment by aeberhart** [comment] 2024-06-11 15:18
we were missing the expression context in the REST call, so user, variable, href etc. were not set

**Comment by pgrill79** [comment] 2024-06-16 11:05
It seems mostly to be fixed

This works now:
`  $species:=$number($.variable.species);
  $call("json_replaceKey", {"data": $all($.variable.db, "breed")[fk_species=$species], "search": "id", "new":"value"});`

Also this works
`$call("json_replaceKey", {"data": $all($.variable.db, "breed")[fk_species=3], "search": "id", "new":"value"});`

For some reason it does not work if i use the variable in the pedicate query:
`$call("json_replaceKey", {"data": $all($.variable.db, "breed")[fk_species=$number($.variable.species)], "search": "id", "new":"value"});`

in that case i get null

**Comment by aeberhart** [comment] 2024-06-19 08:26
Good catch - this has a different root cause in the jsonata implementation:
https://github.com/dashjoin/jsonata-java/issues/45

closing this issue

we track the jsonata update here: #384

**Closed by aeberhart** 2024-06-19 08:26 UTC
Labels: bug

**Comment by aeberhart** [comment] 2024-07-11 15:50
@pgrill79, actually this works as designed. The filter operator changes the $ context. For instance, you are accessing "fk_species" which is the same as "$.fk_species". The top level variable.species must be accessed via $$.variable.species

see https://docs.jsonata.org/programming#built-in-variables
