### ISSUE TITLE
Variables are lost, but session remains when closing the browser

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#369] opened 2024-06-09 06:24 UTC
We set several variables on the login - when the user now closes the browser and opens the site again, he is still logged in but all the variables are "forgotten" which leads to a strange behaviour.

**Comment by aeberhart** [comment] 2024-06-11 07:30
In the browser, there are two kinds of storage (see https://stackoverflow.com/questions/5523140/are-there-any-benefits-to-session-storage-over-local-storage):

[localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) and [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) both extend [Storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage). There is no difference between them except for the intended "non-persistence" of sessionStorage.

That is, the data stored in localStorage persists until explicitly deleted. Changes made are saved and available for all current and future visits to the site.

For sessionStorage, changes are only available per tab. Changes made are saved and available for the current page in that tab until it is closed. Once it is closed, the stored data is deleted.

We store browser authentication in localStore and delete it when you log out.

Variables and Notebooks are stored in the session store.

The rationale for this is that you may want to have two browser windows open that use different variables. E.g. if you're using a variable to store a query filter, you can view two versions of a chart in two windows.

So I guess the problem is, that once you re-open the browser, you're getting the on-login event to re-set the variables, right? I think we have the following options:

1) store variables in localStore - maybe more intuitive but we loose the multi-tab feature
2) introduce session and local variables - flexible but might be hard to understand
3) we're working on an on-load hook which could be used here

**Comment by aeberhart** [comment] 2024-07-02 08:31
Changing the variables to apply to the entire browser, rather than a tab is not feasible. Many use cases rely on having different displays in different tabs.

Introducing setLocal and setSession is too confusing.

We recommend moving the setVariable calls from on-login to onRender on a page. There might be a small performance impact of this, however, this seems to be the most logical and easy fix for this issue.

**Closed by aeberhart** 2024-07-02 08:31 UTC
Labels: documentation
